name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1 : Tests locaux sans Docker
  test_local:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start FastAPI app
        run: |
          source venv/bin/activate
          nohup uvicorn src.api:app --host 127.0.0.1 --port 8000 &

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to be ready at http://127.0.0.1:8000"
          for i in {1..10}; do
            if curl -s http://127.0.0.1:8000 > /dev/null; then
              echo "API is up and running"
              break
            else
              echo "Waiting for API to be ready..."
              sleep 5
            fi
          done

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --maxfail=3 --disable-warnings -q -n 4

  # Job 2 : Tests avec Docker
  test_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run FastAPI app in Docker
        run: |
          docker build -t mlops-api .  # Construire l'image Docker de l'API
          docker run -d -p 8000:8000 --name api-container mlops-api  # Lancer l'API en mode détaché

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to be ready at http://127.0.0.1:8000"
          for i in {1..10}; do
            if curl -s http://127.0.0.1:8000 > /dev/null; then
              echo "API is up and running"
              break
            else
              echo "Waiting for API to be ready..."
              sleep 5
            fi
          done

      - name: Run tests
        run: |
          docker exec -i api-container pytest --maxfail=3 --disable-warnings -q -n 4

      - name: Clean up Docker containers
        run: |
          docker stop api-container
          docker rm api-container

  # Job 3 : Déploiement
  deploy:
    needs: [test_local, test_docker]  # Déploiement après succès des tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run FastAPI app in Docker
        run: |
          docker build -t mlops-api:latest .
          docker run -d -p 8000:8000 --name deployed-container mlops-api:latest

      - name: Verify deployment
        run: |
          echo "Checking deployed API"
          curl -f http://127.0.0.1:8000 || exit 1

      - name: Clean up Docker containers
        run: |
          docker stop deployed-container
          docker rm deployed-container
