name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH for testing
        run: |
          export PYTHONPATH=$(pwd)/src:$PYTHONPATH
          pytest tests/

      #- name: Run tests
      #  run: |
      #    pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t mlops-api .

      - name: Run Docker container
        run: |
          docker run -d --name mlops-api-container -p 8000:8000 mlops-api

      - name: Wait for API to start
        run: |
          sleep 10  # Attente pour le démarrage de l'API

      - name: Test API endpoint
        run: |
          curl --fail http://localhost:8000/predict || exit 1