name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start API in Docker container
      run: |
        docker build -t my_api_image -f Dockerfile .
        docker run -d --name api_container -p 5000:5000 my_api_image
        sleep 15  # Attendre que l'API soit prête

    - name: Check API health
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:5000/health; then
            echo "API is ready!"
            exit 0
          fi
          echo "Waiting for API..."
          sleep 5
        done
        echo "API did not respond in time."
        exit 1

    - name: Wait for API to be ready
      run: |
        for i in {1..10}; do
          curl -s http://localhost:5000/health || true
          if [ $? -eq 0 ]; then break; fi
          sleep 5
        done

    - name: Run tests
      run: |
        . venv/bin/activate
        pytest tests --junitxml=results.xml

    - name: Stop Docker container
      if: always()
      run: |
      docker stop api_container
      docker stop api_container