name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start the FastAPI app
        run: |
          nohup uvicorn src.api:app --host 127.0.0.1 --port 8000 > uvicorn_log.txt 2>&1 &
          sleep 30  # Attendre 10 secondes pour être sûr que l'API est bien lancée
          cat uvicorn_log.txt
          
      - name: Wait for API to be up
        run: |
          for i in {1..10}; do
            if curl --silent --fail http://127.0.0.1:8000/docs; then
              echo "API is up and running!"
              break
            else
              echo "Waiting for API..."
              sleep 5
            fi
          done


      - name: Wait for API to be up
        run: |
          curl --silent --fail http://127.0.0.1:8000/predict || exit 1  # Attendre que l'API soit prête

      - name: Run tests
        run: |
          pytest tests/test_api.py  # Exécuter les tests
