name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start API
        run: |
          python -m uvicorn src.api:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &
          sleep 15  # Temps pour que l'API démarre

      - name: Check API logs
        run: |
          cat uvicorn.log || true

      - name: Debug API startup
        run: |
          ps aux | grep uvicorn

      - name: Check open ports
        run: |
          netstat -tuln

      - name: Wait for API to be ready
        run: |
          timeout=60
          while ! curl -s http://localhost:8000 > /dev/null; do
            sleep 1
            timeout=$((timeout - 1))
            if [ $timeout -le 0 ]; then
              echo "API did not start in time."
              exit 1
            fi
          done

      - name: Run tests
        run: |
          pytest tests/
