name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Vérifier le code du dépôt

      - name: Set up Python
        uses: actions/setup-python@v4  # Utiliser Python 3.9 (ou une version différente si nécessaire)
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Mettre à jour pip
          pip install -r requirements.txt  # Installer les dépendances définies dans requirements.txt

      - name: Run tests
        run: |
          pytest  # Exécuter les tests avec pytest
