jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Docker container for API
      run: |
        docker build -t api_image .
        docker run -d --name api_container -p 5000:5000 api_image

    - name: Wait for API to be ready
      run: |
        for i in {1..10}; do
          curl -s http://localhost:5000/health || true
          if [ $? -eq 0 ]; then break; fi
          sleep 5
        done

    - name: Run tests
      run: |
        . venv/bin/activate
        pytest tests --junitxml=results.xml

    - name: Stop Docker container
      if: always()
      run: docker stop api_container